version: "3.8"
services:
  llm-server:
    build: ./llm-server
    ports:
      - "11434:11434"
    volumes:
      - ./llm-server/models:/app/models  # Mount local models folder inside container

  app:
    build: ./app
    depends_on:
      - llm-server
    environment:
      - GITHUB_TOKEN=your_token_here
