services:
  llm-server:
    build: ./llm-server
    ports:
      - "11434:11434"
    volumes:
      - ./llm-server:/app
      - ./models:/models
    environment:
      - TRANSFORMERS_CACHE=/models/pretrained
      - HF_HOME=/models

  app:
    build: ./app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./models:/models
    depends_on:
      - llm-server
