services:
  llm-server:
    build: ./llm-server
    ports:
      - "11434:11434"
    volumes:
      - ./llm-server:/app
      - ./models:/models
      - ./models/pretrained:/root/.cache/huggingface/transformers
      - ./models/datasets:/root/.cache/huggingface/datasets
    environment:
      - TRANSFORMERS_CACHE=/models/pretrained
      - HF_HOME=/models
      - HF_DATASETS_CACHE=/models/datasets

  app:
    build: ./app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./models:/models
    depends_on:
      - llm-server
